name: AutoTestCI
on: push
jobs:
  test:
    name: AutoTest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Prepare env
      run: |
        sudo apt-get update
        sudo apt-get -yqq install scons qemu-system git
        git clone https://github.com/Guozhanxin/pkg_hello_world.git
        git clone https://github.com/RT-Thread/packages.git

    - name: Start test
      run: |
        echo “bear check start...”
        python3 bear.py check --pkg_path=./pkg_hello_world --pkg_index_path=./packages
        echo “bear check OK！”
        echo “bear build start...”
        python3 bear.py build --pkg_path=./pkg_hello_world --pkg_index_path=./packages
        echo “bear build OK！”
        echo “bear test start...”
        python3 bear.py test  --pkg_path=./pkg_hello_world --pkg_index_path=./packages
        echo “bear test OK！”
